### PR TITLE
feat: add FontAwesome + styling

### PR DESCRIPTION
**Pull request by korhox**

### CODE REVIEW

**Comment by korhox** [comment]
For some reason my commit message on c26a5d6 was left out. It was something like "improve a11y by removing centering".

**Review by Loofn — CHANGES_REQUESTED** [review]
Either I'm blind or could not find it... Website title missing font 'Montserrat'. Was removed in [commit](https://github.com/newbNox/rainbowcreators/pull/7/commits/13ed149402ddc84d808a7d253af70e823195f100)

**Comment by korhox** [comment]
I added the forgotten font back in the last commit

**Review by Loofn — APPROVED** [review]

**Comment by korhox** [comment]
Also this PR fixes issue #6

**Pull request merged**
